apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: subhash707/book-catalog:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://subhash:t5yWZ1UJBWsG88rY1zEtSdMkEiCWMS4R@dpg-cr4gkntsvqrc73b0a3ug-a.oregon-postgres.render.com/db_zyo6"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  type: NodePort
  selector:
    app: book-catalog
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000